[template]
cargo_generate_version = ">=0.10.0"

[placeholders.author]
type = "string"
prompt = "Authors"

[placeholders.email]
type = "email"
prompt = "Email"


[placeholders.gh-username]
type = "string"
prompt = "GitHub username (or organization)"
regex = "^[A-Za-z0-9][A-Za-z0-9-]{0,38}$"

[placeholders.project-description]
type = "string"
prompt = "Project description"
